version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Starting build process..."
      - node app.js &

  post_build:
    commands:
      - echo "Build complete!"

artifacts:
  files:
    - '**/*'
  name: build-artifact-name
  discard-paths: no
